# Integrated Musicianship: A Theory and Aural Skills Method
# OER Music text book, by Sean Butterfield and Miranda Wilson

# jekyll theme adapted from Lanyon, https://github.com/poole/lanyon
# by evanwill

# site info
title: "Integrated Music Theory"
tagline: "2023-24"
description: "an open, interactive, online textbook for college music theory"
keywords: "music theory, OER, university of idaho, inquiry-based"
owner: Sean Butterfield
email: sbutterfield@uidaho.edu
published: 2023
github-repo: 

# urls
url: https://javier.montanana.com
baseurl: /grade5theory

# collections
# each unit of the book is a collection
# each unit collection should be given a name value
collections:
  01-pitches-clefs:
    output: false
    name: 1) Pitches and Clefs
  02-int-scales-keys:
    output: false
    name: 2) Intervals, Scales, and Keys
  aa-intervals:
    output: true
    name: 24) Intervals
  ab-scales:
    output: true
    name: 25) Scales and Keys
  ac-transposing:
    output: false
    name: 26) Transposing
  ad-chromatic-and-enharmonic:
    output: false
    name: 27) Chromatic and Enharmonic
  ae-chords:
    output: false
    name: 28) Chords
#  final-project:
#    output: true
#    name: Final Project Notes and Discussion
#  assignments:
#    output: true
#    name: Assignments

# ignore stuff
exclude: [docs]
