# Integrated Musicianship: A Theory and Aural Skills Method
# OER Music text book, by Sean Butterfield and Miranda Wilson

# jekyll theme adapted from Lanyon, https://github.com/poole/lanyon
# by evanwill

# site info
title: "Music Theory"
tagline: ""
description: "an open online textbook for grade 5 music theory"
keywords: "music theory, OER, ABRSM, grade 5, grade five theory"
owner: Javier Montañana 
email: javier.montanana@gmail.com
published: 2025
github-repo: 

# urls
url: https://javiermontanana.com
baseurl: /grade5theory

# collections
# each unit of the book is a collection
# each unit collection should be given a name value
collections:
  01-basics:
    output: true
    name: 1) The basics
  02-rhythm-and-meter:
    output: true
    name: 2) Rhythm and Metre
  03-intervals:
    output: true
    name: 3) Intervals
  04-scales:
    output: true
    name: 4) Scales and Keys
  05-transposing:
    output: true
    name: 5) Transposing
  06-chromatic:
    output: true
    name: 6) Chromatic Scales
  07-chords:
    output: true
    name: 7) Chords
  08-clefs-and-registers:
    output: true
    name: 8) Clefs and registers
  09-ornaments:
    output: true
    name: 9) Ornaments
#  final-project:
#    output: true
#    name: Final Project Notes and Discussion
  # assignments:
  #   output: true
  #   name: Assignments

# ignore stuff
exclude: [docs]
